# Generated by Django 4.0.5 on 2022-07-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
